# Generated by Django 3.1.3 on 2020-11-07 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_image', models.TextField(null=True)),
                ('scientific_name', models.CharField(max_length=100, null=True)),
                ('nickname', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('acquired', models.DateField(null=True)),
                ('special_instructions', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profile_image', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_date', models.DateField(null=True)),
                ('water_time', models.TimeField(null=True)),
                ('water_repeat', models.IntegerField(null=True)),
                ('water_notification', models.BooleanField(default=True)),
                ('fertilize_date', models.DateField(null=True)),
                ('fertilize_time', models.TimeField(null=True)),
                ('fertilize_repeat', models.IntegerField(null=True)),
                ('fertilize_notification', models.BooleanField(default=True)),
                ('rotate_date', models.DateField(null=True)),
                ('rotate_time', models.TimeField(null=True)),
                ('rotate_repeat', models.IntegerField(null=True)),
                ('rotate_notification', models.BooleanField(default=True)),
                ('repot_date', models.DateField(null=True)),
                ('repot_time', models.TimeField(null=True)),
                ('repot_repeat', models.IntegerField(null=True)),
                ('repot_notification', models.BooleanField(default=True)),
                ('mist_date', models.DateField(null=True)),
                ('mist_time', models.TimeField(null=True)),
                ('mist_repeat', models.IntegerField(null=True)),
                ('mist_notification', models.BooleanField(default=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='app.plant')),
            ],
        ),
        migrations.CreateModel(
            name='PlantImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField()),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.plant')),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='app.user'),
        ),
    ]
