# Generated by Django 3.1.3 on 2020-11-18 19:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20201115_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantimage',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
